image: docker:24.0.5

stages:
    - build-image
    - renovate

build-image:
    stage: build-image

    image: registry.green-rabbit.net:5000/kimata/local_ubuntu:230812D

    script:
        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/font.git private_font
        - mv private_font/* font
        - docker pull ${CI_REGISTRY_IMAGE} || true
        - docker build . -t ${CI_REGISTRY_IMAGE}
        - docker push ${CI_REGISTRY_IMAGE}

renovate:
    stage: renovate
    image:
        name: registry.green-rabbit.net:5000/kimata/local_renovate:36

        entrypoint: [""]
    script:
        - renovate --platform gitlab --token ${RENOVATE_TOKEN} --endpoint ${CI_SERVER_URL}/api/v4 ${CI_PROJECT_PATH}
        # # NOTE: ついでにお掃除
        #  - docker rm $(docker ps -a --filter "status=exited" -q) || true
    rules:
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
              - renovate.json
